version: '3.8'

services:
  web:
    container_name: fastapi_web
    build:
      ./src
    command:
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - template_data:C:/Template_Data/
    ports:
      - 8080:8000
    env_file:
      - ./.env/.env.dev

volumes:
  template_data: